{
 "title": "Alerts Overview",
 "tags": [
  "prometheus",
  "alerting"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size: 24px; font-weight: bold;\">Alerts Overview</div>"
   }
  },
  {
   "title": "Currently Active Alerts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "App Memory Usage vs Alert Threshold",
   "type": "graph",
   "description": "Shows the current memory usage vs the alert threshold value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"sample-app-.*\"}) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Current Memory Usage"
    },
    { "expr": "0.5", "legendFormat": "Alert Threshold (50%)" }
   ]
  },
  {
   "title": "Cluster Memory Usage vs Alert Threshold",
   "type": "graph",
   "description": "Shows the current cluster memory usage vs the alert threshold value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Current Cluster Memory"
    },
    { "expr": "0.7", "legendFormat": "Alert Threshold (70%)" }
   ]
  },
  {
   "title": "Memory Usage vs Alert Thresholds",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"sample-app-.*\"}) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "App Memory"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Cluster Memory"
    }
   ]
  }
 ]
}