apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      # Group alerts by application and alertname
      group_by: ['app', 'alertname']
      
      # Wait 30s to buffer alerts of the same group before sending
      group_wait: 30s
      
      # Wait 5m before sending a notification for new alerts that are added to a group
      group_interval: 5m
      
      # Wait 3h before sending a notification again if it has been already sent
      repeat_interval: 3h
      
      # Default receiver
      receiver: 'null'

    # This receiver does nothing (no notifications)
    receivers:
    - name: 'null'

    # Define detailed information about the alert
    templates:
    - '/etc/alertmanager/config/*.tmpl'