mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.93.0"

config:
  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
  service:
    pipelines:
      metrics:
        exporters: [prometheus]