apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: kubernetes.rules
    rules:
    - alert: HighAppMemoryUsage
      #expr: sum(container_memory_usage_bytes{namespace="default", pod=~"sample-app-.*"}) / sum(node_memory_MemTotal_bytes) > 0.5
      expr: sum(container_memory_usage_bytes{namespace="default", pod=~"sample-app-.*"}) / sum(node_memory_MemTotal_bytes) > 0.01
      #for: 5m
      for: 1m
      labels:
        severity: warning
        app: sample-app
      annotations:
        summary: "High application memory usage"
        description: "Application is using more than 50% of total cluster memory for over 5 minutes."
    
    - alert: HighClusterMemoryUsage
      expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes) > 0.7
      for: 5m
      labels:
        severity: critical
        app: kubernetes
      annotations:
        summary: "High cluster memory usage"
        description: "Cluster memory usage is above 70% for over 5 minutes."
        
    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[15m]) > 3
      for: 10m
      labels:
        severity: warning
        app: sample-app
      annotations:
        summary: "Pod restarting frequently"
        description: "Pod {{ $labels.pod }} has restarted more than 3 times in the last 15 minutes."