tempo:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_compact:
          endpoint: 0.0.0.0:6831
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  storage:
    trace:
      backend: local
  service:
    type: ClusterIP
    ports:
      otlp-grpc: 4317
      otlp-http: 4318
      jaeger-thrift: 14268
      jaeger-grpc: 14250
      jaeger-thrift-compact: 6831