tempo:
  receivers:
    jaeger:
      protocols:
        thrift_http:
          endpoint: 0.0.0.0:14268
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  serviceGraphEnabled: true

service:
  ports:
    - port: 3100
      name: tempo
    - port: 14250
      name: jaeger-grpc
    - port: 14268
      name: jaeger-thrift-http
    - port: 6831
      name: jaeger-thrift-compact
    - port: 6832
      name: jaeger-thrift-binary
    - port: 4317
      name: otlp-grpc
    - port: 4318
      name: otlp-http